apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-standard-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-premium-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefilepremium
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-premium-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefilepremiumnfs
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-netapp-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-fs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs