apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-premium-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefilepremium
  resources:
    requests:
      storage: 100Gi