apiVersion: batch/v1
kind: Job
metadata:
  name: hey
spec:
  template:
    spec:
      containers:
      - name: hey
        image: pcreuwcore.azurecr.io/hey:0.1.4
        args: ["-n","5000","-c","500","-z","10m","http://acisimpleapi.westeurope.azurecontainer.io:3000/api/getVersion"]
        imagePullPolicy: Always
      restartPolicy: Never
  completions: 10
  parallelism: 10
