apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-premium-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Gi